### ISSUE TITLE
Issues pushing a message

### ISSUE THREAD

**Issue by Yonny24** [zoernert/nr-gotify-push#1]
Hi there,

I'm trying out gotify for the first time and trying to push a message from nodered.
Token and server (own) are correct as I can push from watchtower.

I am using a function node before the send gotify node.
I inject a msg.payload = "test" for example but nothing is pushed through.
Please can you point me in the right direction? What node and code do I need to push a message?
Many thanks!

`msg.payload = "Frontyard movement AI - "
return msg;`
![image](https://user-images.githubusercontent.com/64428686/178803875-2f772d07-57da-4c0b-8ab0-8a93c5142e1e.png)

**Comment by zoernert** [comment]
https://github.com/zoernert/nr-gotify-push/issues/2 seems to be related as both problems are on selfhosted nodes. Does your code work if you inject a string directly?
