### ISSUE TITLE
Can not connect to the self-hosted Gotify server

### ISSUE THREAD

**Issue by alexsahka** [zoernert/nr-gotify-push#2]
Can not connect to the self-hosted Gotify server.
![image](https://user-images.githubusercontent.com/7469537/180275718-c3903f63-eab8-4c14-8644-1af5da744a05.png)
![image](https://user-images.githubusercontent.com/7469537/180276477-0b232daa-b671-4a31-8756-2ced74736995.png)

Node red connects with the gotify-notification 
![image](https://user-images.githubusercontent.com/7469537/180276016-eaf6da85-74c8-4ce4-9a73-4b512bf439e8.png)
![image](https://user-images.githubusercontent.com/7469537/180276384-18e53e31-de0b-42f4-93ea-7f64e2f3e891.png)

**Comment by zoernert** [comment]
The red bubble means that you are missing a required configuration-node. Is the message receive node working for you? Or only the sende node?

**Comment by alexsahka** [comment]
Both, Neither send nor receive working.

**Comment by alexsahka** [comment]
My self-hosted Gotify server, working just fine with the https://flows.nodered.org/node/node-red-contrib-gotify

**Comment by alexsahka** [comment]
![image](https://user-images.githubusercontent.com/7469537/180339734-ee86b1f3-310c-4e16-b9a4-6a29c554bc5f.png)
![image](https://user-images.githubusercontent.com/7469537/180339754-58498de8-aee8-4f99-8e1f-baaccbab21e2.png)

App token and Gotify-server field outline are red.

**Comment by toomyem** [comment]
It is important to have trailing slash in Gotify-Server address.

`https://gotify.example.com/`  -> works
`https://gotify.example.com` -> displays error message in node-red's log: "Error: getaddrinfo ENOTFOUND gotify.toomyem.netmessage
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"

This could be quite easily fixed by changing the line from send.js:
`axios.post(config.server+"message?token="+config.token,msg.payload);`
to:
`axios.post(config.server+"/message?token="+config.token,msg.payload);`

**Comment by alexsahka** [comment]
> It is important to have trailing slash in Gotify-Server address.
> 
I have tried with/without trailing slash with the same result. The app token and the Gotify-server field still outline in red.

I think this is interference with the https://flows.nodered.org/node/node-red-contrib-gotify which is installed in the NodeRed

**Comment by alexsahka** [comment]
Just confirmed the  interference with the https://flows.nodered.org/node/node-red-contrib-gotify
 Installed the [nr-gotify-push](https://flows.nodered.org/node/nr-gotify) on testing Nodered and everything is working

**Comment by alexsahka** [comment]
I think these two nodes share the same folder = /node_modules/nr-gotify/
