### ISSUE TITLE
Lack of trailing slash (/) on Gotify-Server input restarts Node-Red

### ISSUE THREAD

**Issue by slarrain** [zoernert/nr-gotify-push#3]
If, on the Gotify-Server url input I add a url without a trailng slash, like `http://192.168.1.200:8011` instead of `http://192.168.1.200:8011/`, Node-Red restarts and the Node doesn't work.

I believe this bug could be easily fixed by adding some sanitization logic on the code.

**Comment by zoernert** [comment]
Should be fixed  in https://github.com/zoernert/nr-gotify-push/commit/e64f3623e0274efd60e00664cb67a7386a717c45 (version 0.5.6) - please validate and get back.
